### ISSUE TITLE
Error: Cannot find module 'gulp-util'

### ISSUE THREAD

**Issue by llcawc** [jerrysu/gulp-rsync#63]
Error after updating version from 009 to 010

[22:12:04] gulp-rsync: Starting rsync to host:domen/www/...
[22:12:04] 'deploy' errored after 16 ms
[22:12:04] Error: Cannot find module 'gulp-util'
Require stack:
- /mnt/c/OSPanel/webwork/domen/node_modules/gulp-rsync/rsync.js
- /mnt/c/OSPanel/webwork/domen/node_modules/gulp-rsync/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at rsync.execute (/mnt/c/OSPanel/webwork/domen/node_modules/gulp-rsync/rsync.js:94:5)
    at DestroyableTransform._flush (/mnt/c/OSPanel/webwork/domen/node_modules/gulp-rsync/index.js:154:19)
    at DestroyableTransform.prefinish (/mnt/c/OSPanel/webwork/domen/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:513:28)
    at DestroyableTransform.emit (node:domain:552:15)
    at prefinish (/mnt/c/OSPanel/webwork/domen/node_modules/readable-stream/lib/_stream_writable.js:619:14)

**Comment by onza** [comment]
Same. Downgrade helps, but not a propper solution.
